function [fitresult, gof] = fitsMeans(tt, mm, st)
%CREATEFITS(TT,MM,ST)
%  Create fits.
%
%  Data for 'means' fit:
%      X Input : tt
%      Y Output: mm
%  Data for 'stds' fit:
%      X Input : tt
%      Y Output: st
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Nov-2016 14:03:14

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'means'.
[xData, yData] = prepareCurveData( tt, mm );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.117156220395989 0.0279344715052759];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Mean Fit' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'Measured mean value', 'Fitted mean', 'Location', 'NorthEast' );
% Label axes
xlabel('Time(year)')
ylabel('Mean value')
grid on

%% Fit: 'stds'.
[xData, yData] = prepareCurveData( tt, st );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Standard Deviation Fit' );
h2 = plot( fitresult{2}, xData, yData );
legend( h, 'Measured std.', 'Fitted std.', 'Location', 'NorthEast' );
% Label axes
xlabel('Time(year)')
ylabel('Standard deviation')
grid on


